name: Build scream receiver for debian
on: [push]
jobs:
  build-debs:
    strategy:
      matrix:
        architecture: [amd64, armhf, arm64]
        debian: [bookworm, trixie]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: debian/latest
          sparse-checkout: |
            Receivers/unix
          sparse-checkout-cone-mode: false
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
          source-dir: Receivers/unix
          artifacts-dir: artifacts
          host-arch: ${{ matrix.architecture }}
          docker-image: debian:${{ matrix.debian }}-slim

      - uses: actions/upload-artifact@v6
        with:
          name: scream-receiver-deb-${{ matrix.debian }}_${{ matrix.architecture }}
          path: artifacts

